name: iLibrary CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    # Inject SECRETS as Environment Variables for the entire job
    env:
      DB_HOST: ${{ secrets.DB_SYSTEM }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_LIB: ${{ secrets.DB_LIB }}
      DB_REMPATH: ${{ secrets.DB_REMPATH }}

    steps:
      # 1. Check out your repository's code, making the .deb file available
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up the specific Python version for the job
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install IBM i Access ODBC Driver from the local file
      - name: Install IBM i Access ODBC Driver
        run: |
          # First, install the necessary unixODBC driver manager
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev

          # Now, install the local .deb package from your repository
          # IMPORTANT: Update the filename below to match the one you added
          sudo apt install -y ./.github/installers/ibm-iaccess-1.1.0.24-1.0.amd64.deb

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pyodbc is needed for the IBM i connection
          python -m pip install -r requirements.txt
          python -m pip install flake8 pytest

      # 5. Lint with flake8
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 6. Test with pytest, which will use the installed ODBC driver
      - name: Test with pytest
        run: |
          pytest app/iLibrary/tests